---
AWSTemplateFormatVersion: 2010-09-09
Description: Assume role to get secret on Central Shared Services
Resources:
  RoleSecretManager:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
            - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AdministratorAccess
      Policies:
        - PolicyName: "CentralSharedAssumeRole"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
            - Effect: Allow
              Action: sts:AssumeRole
              Resource: arn:aws:iam::936992537267:role/central-shared-services-assumedigitalnonprod-iam-role
